#!/bin/bash

export LC_NUMERIC="en_US.UTF-8"

show_help() {
  echo "Usage: bash $0 [-c] [-h] [-r new_omemi:new_omema]"
  echo ""
  echo "Options:"
  echo "  -c    Compile the codes before executing the script"
  echo "  -r    Specify new omemi and omema range (format: min:max)"
  echo "  -h    Show this help message and exit"
}

# Defaults
use_compile=false
custom_range=""

# Parse options
while getopts "chr:" opt; do
  case ${opt} in
    c ) use_compile=true ;;
    r ) custom_range=${OPTARG} ;;
    h ) show_help; exit 0 ;;
    * ) show_help; exit 1 ;;
  esac
done

infile="../data/input/nanosphere_eV.dat"
if [ ! -f "$infile" ]; then
  echo "Error: Input file '$infile' not found!"
  exit 1
fi

# Compile the codes if requested
if $use_compile; then
  echo "> Compiling codes..."
  g++ -Wall -I/usr/local/include -L/usr/local/lib ../src/frohlich.cxx -o ../bin/sfr -lgsl -lgslcblas -lm -larmadillo
  g++ -Wall -I/usr/include/ -L/usr/local/lib ../src/ome_al_p3.cxx -o ../bin/oap -lgsl -lgslcblas -lm -larmadillo
  g++ -Wall -I/usr/include/ -L/usr/local/lib ../src/omeG_p3.cxx -o ../bin/oGp -lgsl -lgslcblas -lm -larmadillo
  echo "> ...Done!"
fi

alifol="../img/alp_p3_emi/"
one=1.e-30

read a Dome ome21 G omemi omema metal model gain_model solvent E0 < "$infile"

# Override omemi and omema if custom range is set
if [ ! -z "$custom_range" ]; then
  newomemi=$(echo "$custom_range" | cut -d ':' -f 1)
  newomema=$(echo "$custom_range" | cut -d ':' -f 2)
else
  newomemi=$omemi
  newomema=$omema
fi

fro=(`../bin/sfr`)
omeG=${fro[0]}
Gth=${fro[1]}

focurr="$metal-in-$solvent/"
echo "> Emission threshold Gth = $Gth"

# BOUNDARY MAPS
echo "> Generating boundary maps..."
{
    echo "$a $Dome $omeG $G $newomemi $newomema $metal $model $gain_model $solvent $E0"
    echo "# r Dome ome0 G omemi omema mtl mdl atv sol E0"
    echo "** WARNING: This file was automatically edited by $0."
    echo "** Do not edit this file manually until the process ends."
} > $infile

../bin/oGp
ogpfol="../img/oGp/"
mnewdir="$ogpfol$focurr"
rm -fr "$mnewdir"
mkdir -p "$mnewdir"
gnuplot emi_bndr.gp
mv "$ogpfol"*.png "$mnewdir"

# SPECTRA
anewdir="$alifol$focurr"
echo "> Generating emission spectra..."
rm -fr "$anewdir"
mkdir -p "$anewdir"
mkdir -p "$mnewdir/map_bdr"

gifdir="../img/GIF/$focurr"
rm -fr "$gifdir"
mkdir -p "$gifdir/alpha"

for ii in {0..20}
  do
    iG=$(echo "$ii*0.1" | bc -l)
    iG=$(printf '%.3f' $iG)
    iname=$(printf "%03d" $ii)
    mG=$(echo "$iG*$Gth" | bc -l)
    echo -e "   > Emission spectrum for G = $iG * Gth = $mG"
    {
        echo "$a $Dome $omeG $mG $newomemi $newomema $metal $model $gain_model $solvent $E0"
        echo "# r Dome ome0 G omemi omema mtl mdl atv sol E0"
        echo "** WARNING: This file was automatically edited by $0."
        echo "** Do not edit this file manually until the process ends."
    } > $infile
    ../bin/oap
    gnuplot emi_al.gp
    mv ../img/emi_al.pdf "$anewdir/emi_${iG}Gth.pdf"
    convert -density 300 "$anewdir/emi_${iG}Gth.pdf" "$anewdir/emi_${iname}.png"
    rm "$anewdir/emi_${iG}Gth.pdf"

    gnuplot -c emi_bndr_step.gp "$mG"
    mv "$ogpfol/iso_alka_step.png" "$mnewdir/map_bdr/emi_${iname}.png"

    convert -resize x940 "$anewdir/emi_${iname}.png" ../img/temp0.png
    convert -resize x940 "$mnewdir/map_bdr/emi_${iname}.png" ../img/temp1.png
    convert +append ../img/temp0.png ../img/temp1.png "$gifdir/alpha/emi_${iname}.png"
    rm ../img/temp0.png ../img/temp1.png
  done

convert -delay 20 -loop 0 -dispose previous "$gifdir/alpha"/*.png "$gifdir/alpha.gif"

# Reset input file
echo "> Resetting original input file..."
{
    echo "$a $Dome $ome21 $G $omemi $omema $metal $model $gain_model $solvent $E0"
    echo "# r Dome ome0 G omemi omema mtl mdl atv sol E0"
} > $infile

echo "> Done!"

exit 0
