#!/bin/bash
# steady_state_gth.bash
# Runs Frohlich + steady_state at a few gain factors, while TEMPORARILY overwriting
# ../data/input/nanosphere_eV.dat and restoring it exactly on exit (even on Ctrl+C).

set -euo pipefail
export LC_NUMERIC="en_US.UTF-8"

script_dir="$(cd "$(dirname "$0")" && pwd)"
cd "$script_dir" || exit 1

compile_requested=false
range_override=""

show_help() {
    echo "Usage: bash $0 [-c] [-h] [-r omemi:omema]"
    echo ""
    echo "Options:"
    echo "  -c, --compile   Compile the codes before executing the script"
    echo "  -h, --help      Show this help message and exit"
    echo "  -r, --range     Override omemi:omema (eV) e.g. 2.0:3.5"
}

while [ $# -gt 0 ]; do
    case "$1" in
        -c|--compile)
            compile_requested=true
            shift
            ;;
        -h|--help)
            show_help
            exit 0
            ;;
        -r|--range)
            if [ -z "${2:-}" ]; then
                echo "Error: -r|--range requires an argument in the form omemi:omema" >&2
                exit 1
            fi
            range_override="$2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        -*)
            echo "Unknown option: $1" >&2
            show_help
            exit 1
            ;;
        *)
            echo "Unexpected argument: $1" >&2
            show_help
            exit 1
            ;;
    esac
done

if [ -n "$range_override" ] && [[ "$range_override" != *:* ]]; then
    echo "Error: -r|--range requires omemi:omema" >&2
    exit 1
fi

# --- Targets ---
bin_targets=(../bin/fro ../bin/sts)
src_targets=(../src/frohlich.cxx ../src/steady_state.cxx)

missing=()
missing_exec=false

if [ "$compile_requested" = true ]; then
    for src in "${src_targets[@]}"; do
        [ -f "$src" ] || missing+=("$src (source)")
    done
else
    for bin in "${bin_targets[@]}"; do
        if [ ! -x "$bin" ]; then
            missing_exec=true
            missing+=("$bin (executable)")
        fi
    done
fi

if [ ${#missing[@]} -gt 0 ]; then
    if [ "$compile_requested" = true ]; then
        echo "> Compilation requested but the following files are missing:"
    else
        echo "> Missing required files:"
    fi
    for item in "${missing[@]}"; do
        echo "  - $item"
    done
    if [ "$compile_requested" != true ] && [ "$missing_exec" = true ]; then
        echo "> Hint: rerun with the -c flag to rebuild the executables."
    fi
    exit 1
fi

if [ "$compile_requested" = true ]; then
    echo
    echo "> Compiling codes..."
    g++ -Wall -I/usr/local/include -I/usr/include/eigen3 -L/usr/local/lib ../src/frohlich.cxx -o ../bin/fro -lgsl -lgslcblas -lm -larmadillo
    g++ -Wall -I/usr/local/include -L/usr/local/lib ../src/steady_state.cxx -o ../bin/sts -lgsl -lgslcblas -lm -larmadillo
    echo "> ...Done!"
    echo
fi

# --- Input file handling ---
file_path="../data/input/nanosphere_eV.dat"
if [ ! -f "$file_path" ]; then
    echo "Error: input file not found: $file_path" >&2
    exit 1
fi

echo "> WARNING: $file_path will be temporarily overwritten during the calculations."
bak="$(mktemp)"
cp -f "$file_path" "$bak"
trap 'mv -f "$bak" "$file_path"' EXIT INT TERM

# Read the canonical input format (nanosphere):
# a Dome ome0 G omemi omema mtl mdl atv sol E0
read -r a Dome ome0 G omemi omema mtl mdl atv sol E0 < "$file_path"
orig_omemi="$omemi"
orig_omema="$omema"

# Optionally override emission scan range
if [ -n "$range_override" ]; then
    IFS=: read -r omi oma <<< "$range_override"
    if [ -z "${omi:-}" ] || [ -z "${oma:-}" ]; then
        echo "Error: -r|--range requires omemi:omema" >&2
        exit 1
    fi
    omemi="$omi"
    omema="$oma"
fi

# Export gnuplot xrange helper used elsewhere
mkdir -p ../data/output
printf "set xrange [%s:%s]\n" "$omemi" "$omema" > ../data/output/emission_range.gp

write_input() {
    local ome0_val="$1"
    local G_val="$2"
    local omemi_val="$3"
    local omema_val="$4"
    {
        echo "$a $Dome $ome0_val $G_val $omemi_val $omema_val $mtl $mdl $atv $sol $E0"
        echo "# a Dome ome0 G omemi omema mtl mdl atv sol E0"
        echo "** WARNING: This file was automatically edited by $0."
        echo "** Do not edit this file manually until the process ends."
    } > "$file_path"
}

# --- Run frohlich to get passive resonance & threshold ---
write_input "$ome0" "$G" "$omemi" "$omema"

fro_output=( $("../bin/fro") )
ome_sp="${fro_output[0]:-}"
Gth="${fro_output[1]:-}"

if [ -z "$ome_sp" ] || [ -z "$Gth" ]; then
    echo "Error: frohlich calculation failed (ome_sp or Gth empty)." >&2
    exit 1
fi

echo "> frohlich frequency ome_sp = $ome_sp"
echo "> emission threshold Gth = $Gth"
echo

# --- Run steady_state for a few gain factors ---
gain_factors=(1.1 1.5 1.9)

for factor in "${gain_factors[@]}"; do
    new_G="$(echo "$factor * $Gth" | bc -l)"
    echo "> Running steady_state for G = $factor * Gth = $new_G"
    write_input "$ome_sp" "$new_G" "$omemi" "$omema"

    "../bin/sts"

    if [ ! -f "../data/output/eigenvalues.dat" ]; then
        echo "Error: ../data/output/eigenvalues.dat not found after steady_state." >&2
        exit 1
    fi

    tag="${factor/./p}"
    cp "../data/output/eigenvalues.dat" "../data/output/eigenvalues_G${tag}Gth.dat"
done

echo
echo "> Done! (Original input file was restored automatically.)"
