#!/usr/bin/env bash
set -euo pipefail

export LC_NUMERIC="en_US.UTF-8"

# --- paths (assumes script is launched from ../src as in your draft) ---
SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SRC_DIR/.." && pwd)"

INPUT_FILE="$ROOT_DIR/data/input/nanosphere_eV.dat"
TIME_FILE="$ROOT_DIR/data/input/time.dat"

BIN_DIR="$ROOT_DIR/bin"
OUT_DIR="$ROOT_DIR/data/output"
IMG_DIR="$ROOT_DIR/img"
SCRIPTS_DIR="$ROOT_DIR/scripts"

# --- sanity checks ---
[[ -f "$INPUT_FILE" ]] || { echo "Error: input file not found: $INPUT_FILE" >&2; exit 1; }
[[ -f "$TIME_FILE"  ]] || { echo "Error: time file not found:  $TIME_FILE"  >&2; exit 1; }

mkdir -p "$BIN_DIR" "$OUT_DIR" "$IMG_DIR"

# --- read parameters from nanosphere file (first line only) ---
# Format expected:
# a Dome ome_0 G omemi omema mtl mdl active sol E0
read -r a Dome ome_0 G omemi omema mtl mdl active sol E0 < "$INPUT_FILE"

# --- read time parameters ---
read -r T tpump < "$TIME_FILE"

# --- backup + trap restore ---
echo "> WARNING: $INPUT_FILE will be temporarily overwritten during the calculations."
bak="$(mktemp)"
cp -f "$INPUT_FILE" "$bak"
trap 'mv -f "$bak" "$INPUT_FILE"' EXIT INT TERM

write_input() {
    local ome0_val="$1"
    local G_val="$2"
    local omemi_val="3."
    local omema_val="3.5"
    {
        echo "$a $Dome $ome0_val $G_val $omemi_val $omema_val $mtl $mdl $active $sol $E0"
        echo "# a Dome ome0 G omemi omema mtl mdl active sol E0"
        echo "** WARNING: This file was automatically edited by $(basename "$0")."
        echo "** Do not edit this file manually until the process ends."
    } > "$INPUT_FILE"
}

# --- compile ---
echo "> Compiling selected sources..."
g++ -Wall -I/usr/local/include -I/usr/include/eigen3 -L/usr/local/lib \
  "$ROOT_DIR/src/frohlich.cxx" -o "$BIN_DIR/fro" -lgsl -lgslcblas -lm -larmadillo

g++ -Wall -I/usr/local/include -I/usr/include/eigen3 -L/usr/local/lib \
  "$ROOT_DIR/src/steady_state.cxx" -o "$BIN_DIR/sts" -lgsl -lgslcblas -lm -larmadillo

g++ -Wall -I/usr/local/include -I/usr/include/eigen3 -L/usr/local/lib \
  "$ROOT_DIR/src/num_time.cxx" -o "$BIN_DIR/num" -lgsl -lgslcblas -lm -larmadillo

g++ -Wall -I/usr/local/include -I/usr/include/eigen3 -L/usr/local/lib \
  "$ROOT_DIR/src/anl_time.cxx" -o "$BIN_DIR/anl" -lgsl -lgslcblas -lm -larmadillo
echo "> Compilation complete."

# --- run frohlich (passive resonance & threshold) ---
# Restore "baseline" input first (ome_0, G as in file)
write_input "$ome_0" "$G"

echo "> Running frohlich..."
mapfile -t fro_output < <("$BIN_DIR/fro")

# fro_output may be printed as a single line with multiple numbers.
# We'll just tokenize it safely:
fro_tokens=()
for line in "${fro_output[@]}"; do
  for tok in $line; do fro_tokens+=("$tok"); done
done

ome_th="${fro_tokens[0]:-}"
Gth="${fro_tokens[1]:-}"
ome_sp="${fro_tokens[2]:-}"   # if your fro prints it
ome_sp0="${fro_tokens[3]:-}"  # optional extra

[[ -n "$ome_th" && -n "$Gth" ]] || {
  echo "Error: frohlich output did not contain at least (ome_th, Gth)." >&2
  echo "Raw output was:" >&2
  printf '%s\n' "${fro_output[@]}" >&2
  exit 1
}

echo "> frohlich: ome_th=$ome_th eV, Gth=$Gth"
if [[ -n "$ome_sp" ]]; then
  echo "> frohlich: ome_sp=$ome_sp eV"
fi
if [[ -n "$ome_sp0" ]]; then
  echo "> frohlich: ome_sp0=$ome_sp0 eV"
fi

# --- pick operating point ---
new_G="$(echo "0.2 * $Gth" | bc -l)"


write_input "$ome_th" "$new_G"
echo "> Running steady_state for G = 0.2 * Gth = $new_G (ome0=$ome_th)"
"$BIN_DIR/sts"
  cmpcname="../data/output/compounds.dat"
  # Create the background data
  awk '{
      if (NR > 7) { 
          for (i = -1; i <= 1; i++) { 
          print $1, i, ($5 < 0 ? -$5 : $5) 
          } 
          print ""
          }
      }' $cmpcname > "../data/output/background.dat"
      
omega="$(echo "1.005 * $ome_th" | bc -l)"
echo "> Running time-dependent codes for omega = 1.005 * omega_th = $omega eV..."

echo "$omega" > "$OUT_DIR/omega.dat"

# --- numerical ---
"$BIN_DIR/num" "$omega"

# gnuplot for numerical
(
  cd "$SCRIPTS_DIR"
  gnuplot "numtime.gp"
)
echo "> Check $IMG_DIR/intime.pdf, then press any key to continue..."
read -r -n 1 -s

# --- analytical ---
"$BIN_DIR/anl" "$omega"

# gnuplot for analytical (script path in your draft was inconsistent)
(
  cd "$SCRIPTS_DIR"
  gnuplot "anltime.gp"
)
echo "> Check $IMG_DIR/intime_anl.pdf"
